// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3j3si-M-mJ55gVHg0p7KjmTQUSWZW3m0',
    appId: '1:335839091282:android:ee768f67adef06fb68dd8b',
    messagingSenderId: '335839091282',
    projectId: 'chat1-7f804',
    storageBucket: 'chat1-7f804.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5uGqTPFc-Ti5KhTWFhT80IClCBYYRDwE',
    appId: '1:335839091282:ios:2e6812538e04943a68dd8b',
    messagingSenderId: '335839091282',
    projectId: 'chat1-7f804',
    storageBucket: 'chat1-7f804.appspot.com',
    iosBundleId: 'com.example.flutterFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5uGqTPFc-Ti5KhTWFhT80IClCBYYRDwE',
    appId: '1:335839091282:ios:2e6812538e04943a68dd8b',
    messagingSenderId: '335839091282',
    projectId: 'chat1-7f804',
    storageBucket: 'chat1-7f804.appspot.com',
    iosBundleId: 'com.example.flutterFront',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs9NSYy9eI33NMpKZiBbsQGRV0MkEobbM',
    appId: '1:335839091282:web:0472630f3c6670e568dd8b',
    messagingSenderId: '335839091282',
    projectId: 'chat1-7f804',
    authDomain: 'chat1-7f804.firebaseapp.com',
    storageBucket: 'chat1-7f804.appspot.com',
  );

}